[platformio]
src_dir = ColonyCounterCapture
default_envs = esp32cam

[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.0
    adafruit/Adafruit BME280 Library @ ^2.2.4
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    adafruit/RTClib @ ^2.1.4

build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
